### ISSUE TITLE
java.lang.NullPointerException: Ticking block entity(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [faceofcat/Mekfarm#10]
mek farm: mekfarm-1.11.2-0.3.0-HF
tesla lib: tesla-core-lib-1.11.2-0.3.0
tesla : Tesla-1.11-1.3.0.51
forge: 1.11.2-2253
crash report:
[crash-2017-03-06_07.51.08-client.txt](https://github.com/faceofcat/Mekfarm/files/819737/crash-2017-03-06_07.51.08-client.txt)

**Comment by faceofcat** [comment]
I think I fixed this a long long time ago... :)
