### ISSUE TITLE
[Bug] Exception upon start-up in 1.10.2

### ISSUE THREAD

**Issue by omega025** [faceofcat/Mekfarm#12]
When starting up Minecraft 1.10.2 with version 0.4.0 of Mekfarm, game crashes with an exception and the following error message:

> The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
>Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MekFarm (mekfarm)

**Comment by faceofcat** [comment]
if this still happens on latest versions of the mod and of Tesla Core Lib... can you please also send me the full error?

thanks

**Comment by omega025** [comment]
Downloaded the most up-to-date versions of Mekfarm and the Tesla Core Lib, and the crash upon startup (without any other mods) still occurs.

As requested, the full error report is below:

> ---- Minecraft Crash Report ----
> // Surprise! Haha. Well, this is awkward.
> 
> Time: 5/4/17 11:06 AM
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MekFarm (mekfarm)
> Caused by: java.lang.RuntimeException: Invalid shaped ore recipe: x x,  y , x x, x, cropWheat, y, null, 1xitem.mekfarm_animal_filter@0
> 	at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:135)
> 	at mekfarm.items.AnimalFilterItem.getRecipe(AnimalFilterItem.java:21)
> 	at net.ndrei.teslacorelib.items.RegisteredItem.getRecipes(RegisteredItem.java:48)
> 	at net.ndrei.teslacorelib.items.RegisteredItem.register(RegisteredItem.java:31)
> 	at mekfarm.common.ItemsRegistry.createItems(ItemsRegistry.java:19)
> 	at mekfarm.common.CommonProxy.preInit(CommonProxy.java:17)
> 	at mekfarm.client.ClientProxy.preInit(ClientProxy.java:20)
> 	at mekfarm.MekfarmMod.preInit(MekfarmMod.java:86)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
> 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
> 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
> 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
> 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
> 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.10.2
> 	Operating System: Mac OS X (x86_64) version 10.12.4
> 	Java Version: 1.8.0_74, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 144325112 bytes (137 MB) / 354095104 bytes (337 MB) up to 2134114304 bytes (2035 MB)
> 	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.32 Powered by Forge 12.18.3.2185 6 mods loaded, 6 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
> 	UCH	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
> 	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
> 	UCE	teslacorelib{0.7.0} [Tesla Core Lib] (tesla-core-lib-1.10.2-0.7.0.jar) 
> 	UCE	mekfarm{0.0.1} [MekFarm] (mekfarm-1.10.2-0.7.0.jar) 
> 	Loaded coremods (and transformers):

**Comment by faceofcat** [comment]
what if you also add this mod: [TESLA](https://minecraft.curseforge.com/projects/tesla) ?

**Comment by omega025** [comment]
With that mod added, game starts up normally.

**Comment by faceofcat** [comment]
well... Tesla should be a required library for Tesla Core Lib... not sure why it wouldn't be installed by Curse... :S...

and if you were doing a manual install of the mod... well... glad it works fine now... :)

**Comment by omega025** [comment]
This was a manual install for me.  The Tesla Core Lib was the only required dependency I saw listed on the Curseforge page - perhaps the overview text on Curseforge should be updated to mention that Tesla is also needed?
