### ISSUE TITLE
Possible to work with Moofluids?

### ISSUE THREAD

**Issue by Mazerwulf** [faceofcat/Mekfarm#14]
I tried the AutoFarmer with Moofluids and unfortunately it just milks the cows instead of the fluids they are associated with. Would there be any chance to add a compatibility with Moofluids?

pretty please :D

**Comment by faceofcat** [comment]
sure thing... I'll add that to my list.

thanks.

**Comment by faceofcat** [comment]
please check Mekfarm 0.7.1... should be able to milk Moo Fluid Cows now... :)
