### ISSUE TITLE
crop cloner - when machine gets full, items are output to the world

### ISSUE THREAD

**Issue by DoomSquirter** [faceofcat/Mekfarm#15]
using EIO conduits.  Have tried setting each side separately and not put items/water/power on same side but none have made a difference.

running mekfarm-1.10.2-0.4.0 on SMP
pack Craft of the Titans 1.04
using EIO conduits for everything.

Normally I'd say this was an EIO issue except I'm not having any problems with the conduits stop working with anything but the crop cloners (all I've really used alot from your mod thus far).   Others are having exact same issue on server.

This could be a new issue but I'll address it here:  Reason I notice when it stops working is because when output is full, items are ejected into the world, which is I guess a second issue and pretty bad form.  Probably should just stop processing instead? 

Love the mod btw.  It fits a very nice niche and is a welcome sight to 1.10+

**Comment by DoomSquirter** [comment]
addendum to issue.  one person and only one hasn't had this happen to them but he's using the top of the crop cloner for all three (power/water/items) and nobody else has done it this way.  I'll give that a try and update to see if I still have an issue using the top side.

**Comment by DoomSquirter** [comment]
edited issue to reflect secondary issue instead (used to be crop cloner - conduits are connected but after a while need to be replaced to pull items out)

so I myself haven't had any issues with EIO on the server with this pack except the crop cloner which others have had.  but have now started to see similar issues with EIO conduits connected to other devices having similar issues to what I described so this problem might fall into their realm and not yours most likely.  

Regardless, if you could change the behavior of how the crop cloner spills item into the world when the buffer is filled, that'd be appreciated.

**Comment by DoomSquirter** [comment]
so I've been running a crop cloner for 24 hours now with all eio conduits going through the top and haven't had a single issue at all.  I have no idea why this orientation works when the others cause sporatic problems.  so even if there's an issue that deals with EIO conduits, I think there's a nuance about the TOP side working fine that bears looking into.  Thanks

**Comment by faceofcat** [comment]
the "when full, spill items into the world" is kind of a feature for all machines... :)

in the near feature I will make sure to add a config option for this.


about the EIO conduits only working from the  TOP... I have no idea... I'll have to check it out... will try it for myself and see if I find the problem.

thanks for reporting... and sorry for the late reply... for some reason github doesn't send me notifications about issues... :S

**Comment by DoomSquirter** [comment]
no worries, I never keep up with github replies myself regardless of whether I'm notified or not lol

So, only connecting to top working is not the case.  Even with connections at top still causes issues, It did hold out for 3+ days till it finally backed up tho.  I am more leaning towards this being an EIO issue but it really is hard for me to pin down circumstances that cause this to happen.  

As far as spilling items into the world, I can see on ssp how that might be a good thing to punish user but on smp, that causes TPS lag, possibly even when person isn't even online depending on chunkloading, and imho isn't very server friendly.  Especially if person has a bunch of them.

**Comment by DoomSquirter** [comment]
so, update to conduit issue.  def not your problem:  
https://github.com/LatvianModder/FTBUtilities/issues/360
https://github.com/SleepyTrousers/EnderIO/issues/4155

but I'd still like to give my +1 to not having items spill out on the ground by default, or at the very least having a config option

**Comment by faceofcat** [comment]
yes... will get that into a config file.... :)

**Comment by faceofcat** [comment]
please check Mekfarm 0.7.1... there is a config option for this...

it's currently WIP, so... the bad news is that the items will be lost if not spawned in the world... but that will be fixed soon... :)
