### ISSUE TITLE
bop biom integration crash 

### ISSUE THREAD

**Issue by 5kedone** [faceofcat/Mekfarm#6]
as above with latest version of mekfarm i get a crash this is on 1.11

**Comment by faceofcat** [comment]
hey mate...

could you please attach the mod list that you are loading and a crash log here?

thanks!

**Comment by faceofcat** [comment]
not sure what your issue is...

but please test with latest version (Mekfarm : 1.11 - 0.0.5 - HF) and tell me if it still happens.

if it is, please attach more details.

**Comment by 5kedone** [comment]
Don't worry will post crash log and alike today sorry was busy with family
and spent the day tracking another bug lol so wanted a break , will post
logs ect after check all updates today

**Comment by 5kedone** [comment]
here you go everything updated and same crash http://pastebin.com/gNeLb7kF

**Comment by faceofcat** [comment]
seems that the tesla core lib is not loaded?... is that part of your pack?... is a requirement for latest mekfarm for 1.11...

https://minecraft.curseforge.com/projects/tesla-core-lib

**Comment by 5kedone** [comment]
oh woops man cant believe i missed that

**Comment by faceofcat** [comment]
no worries :)... just let me know if it still fails after you add that.

**Comment by 5kedone** [comment]
All good now WOW can't bielve I missed that ....I'll go sit in corner
wearing my special hat lol

**Comment by faceofcat** [comment]
:D :D ... that's ok... glad it works now!
