### ISSUE TITLE
crash on server start up(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [faceofcat/Mekfarm#8]
forge:1.11.2-2233
mekfarm version:mekfarm-1.11.2-0.2.0
teslacore lib:tesla-core-lib-1.11.2-0.2.0
crash report:
[crash-2017-02-20_16.04.21-server.txt](https://github.com/faceofcat/Mekfarm/files/786592/crash-2017-02-20_16.04.21-server.txt)
server latest:
http://puu.sh/ubaf0/705d503b41.txt

**Comment by faceofcat** [comment]
should be fixed in Mekfarm : 1.11.2 - 0.2.0 - HF

thanks!
