### ISSUE TITLE
[1.10.2] [SMP] Crash on server startup

### ISSUE THREAD

**Issue by b0bst3r** [faceofcat/Mekfarm#9]
http://pastebin.ubuntu.com/24114256/

mekfarm-1.10.2-0.3.0
tesla-core-lib-1.10.2-0.3.0.jar
Forge 12.18.3.2221

**Comment by Minizbot2012** [comment]
I can also confirm the same error for 1.11.2

**Comment by faceofcat** [comment]
thanks :)

should be fixed in "1.1X.2 - 0.3.0 - HF" versions.

I always forget to test in server/client environment.
